### ISSUE TITLE
[planning] Appkit Roadmap

### ISSUE THREAD

**Issue by aslesarenko** [aslesarenko/ergo-appkit#19]
- [ ] Commands processing layer implemented
  - [ ] Refactor Commands towards reusable components
  - [ ] Implement Commands layer API
  - [ ] Commands API is fully documented
- [ ] blog-post is published (Introduction to Commands API)
  - [ ] blog-post draft
  - [ ] blog-post is reviewed and tags assigned
  - [ ] blog-post is converted to site page
  - [ ] marketing is planned

**Comment by aslesarenko** [comment]
No longer relevant to the main use cases of Appkit
